openMF/mobile-wallet

- app/build.gradle
- build.gradle
- core/build.gradle
- gradle/wrapper/gradle-wrapper.properties
- mifospay/build.gradle
Update build tools and remove apt plugin
> update build tools

- build.gradle
- mifospay/src/main/res/layout/activity_login.xml
Fixes #18 
As discussed that sign up process is not supported yet in the backend therefore removed the sign up button from the LoginActivity.
> Removed the SignUp button

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/ui/TransferFragment.java
Fixes #21 
Added a prompt message if either the Amount or the VPA field is left blank.
> Fixed App crash on clicking Send Money

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/base/BaseFragment.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/common/TransferContract.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/common/presenter/MakeTransferPresenter.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/common/ui/MakeTransferFragment.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/HomeContract.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/presenter/TransferPresenter.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/ui/TransferFragment.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/utils/Constants.java
Fixes #60 
Add snackbars for showing:
- Invalid amount transfer
- Insufficient balance
- Error finding Virtual Payment Address
> Add error snackbar for transferring money

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/editprofile/EditProfileContract.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/editprofile/presenter/EditProfilePresenter.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/editprofile/ui/EditProfileActivity.java
- mifospay/src/main/res/drawable/ic_photo_library.xml
- mifospay/src/main/res/drawable/ic_remove.xml
- mifospay/src/main/res/layout/activity_edit_profile.xml
- mifospay/src/main/res/layout/dialog_change_profile_picture.xml
Fixes #74
Gif preview:
- [ x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
- [ x] Run the unit tests with `./gradlew check` to make sure you didn't break anything
I've ran ./gradlew check and got
```
:core:findbugs
No files to be analyzed
```
- [x ] If you have multiple commits please combine them into one commit by squashing them.
> Feat: Add BottomSheetDialog with modify profile image options

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/savedcards/ui/AddCardDialog.java
- mifospay/src/main/res/layout/dialog_add_card.xml
- mifospay/src/main/res/values/strings.xml
Fixes #56 
**Changes**
- Add checks to show that a field is required if it's empty.
- Show a toast if an expired card is being added.
> Feat: Add checks while storing cards

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/bank/ui/LinkBankAccountActivity.java
Fixes #62 
Since the scrolling is not very smooth in this app, I had added some code so that we can scroll smoothly.
> fix:In UI scrolling is very hard 

- mifospay/build.gradle
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/editprofile/ui/EditProfileActivity.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/ui/ProfileFragment.java
- mifospay/src/main/res/layout/activity_edit_profile.xml
- mifospay/src/main/res/layout/fragment_profile.xml
- mifospay/src/main/res/values/dimens.xml
Fixes #83 
Please Add Summary of what changes you have made. (Optional)
User's profile image is circle now, hooray!
> Fix: #83 User's profile image is circle now

- config/quality/findbugs/android-exclude-filter.xml
- config/quality/quality.gradle
- core/build.gradle
- core/src/main/java/org/mifos/mobilewallet/core/data/fineract/api/FineractApiManager.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/bank/presenter/BankAccountsPresenter.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/bank/presenter/LinkBankAccountPresenter.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/bank/ui/BankAccountsActivity.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/bank/ui/LinkBankAccountActivity.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/editprofile/ui/EditProfileActivity.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/merchants/ui/MerchantsFragment.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/utils/FileUtils.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/utils/NotificationUtils.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/utils/Utils.java
Fixes #85
Fix `./gradlew check`.
> Fix: Error while running Gradle check

- .travis.yml
> Feat: Add .travis.yml config

- mifospay/src/main/AndroidManifest.xml
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/faq/FAQContract.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/faq/FAQListAdapter.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/faq/presenter/FAQPresenter.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/faq/ui/FAQActivity.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/ui/ProfileFragment.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/utils/Constants.java
- mifospay/src/main/res/layout/activity_faq.xml
- mifospay/src/main/res/layout/faq_list_child.xml
- mifospay/src/main/res/layout/faq_list_group.xml
- mifospay/src/main/res/menu/menu_profile.xml
- mifospay/src/main/res/values/strings.xml
(currently with dummy data)
Feat #77
Replaced the menu in profile with a 3-dot button displaying a drop-down with 3 options. FAQ, Edit Profile and Settings.
Created FAQ Activity with several questions/answers displayed in dropdowns as well (ExpandableListViews).
Note: gradle build failed but its errors have nothing to do with this PR - it must be handled in another PR.
> Feat #77: Added FAQ area

- mifospay/src/main/res/drawable/drawable_editable_image_hint.xml
- mifospay/src/main/res/drawable/ic_camera.xml
- mifospay/src/main/res/layout/activity_edit_profile.xml
- mifospay/src/main/res/values/dimens.xml
Fixes #100 
Please Add Summary of what changes you have made. (Optional)
* Changed profile image size (made it bigger)
* Add camera icon for the edit mode to inform user he can easily modify current profile image by tapping on it
> Feat: Improve ui/ux in edit profile activities

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/editprofile/ui/EditProfileActivity.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/ui/ProfileFragment.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/utils/Constants.java
> Feat: #127 Connect Profile with EditProfile

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/presenter/HomePresenter.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/transactions/TransactionsContract.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/transactions/TransactionsHistory.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/transactions/presenter/TransactionsHistoryPresenter.java
> Fix: #128 Fix bug in home fragment

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/passcode/ui/PassCodeActivity.java
**Fixes #149** 
**Please Add Summary of what changes you have made.(Optional)**
Added the missing code to the show Toaster method in Passcode Activity.
> Fix#149 Added the missing code for showToaster method

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/base/BaseActivity.java
- mifospay/src/main/res/anim/custom_fade_in.xml
- mifospay/src/main/res/anim/custom_fade_out.xml
- mifospay/src/main/res/values/integers.xml
> Feat: #144 Add transitions between fragments

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/ui/MainActivity.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/ui/PaymentsFragment.java
> Fix: #146 Change title of Payments section

- mifospay/src/main/res/values/strings.xml
> fix: Unescaped apostrophe in string

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/ui/FinanceFragment.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/kyc/ui/KYCDescriptionFragment.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/kyc/ui/KYCLevel1Fragment.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/kyc/ui/KYCLevel2Fragment.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/kyc/ui/KYCLevel3Fragment.java
- mifospay/src/main/res/drawable/ic_tick.xml
- mifospay/src/main/res/layout/fragment_kyc.xml
- mifospay/src/main/res/values/colors.xml
- mifospay/src/main/res/values/strings.xml
Fixes 
#140 
Screenshots
Summary
Integrated the kyc section in finance tab and changed the design as per requirement
> integrated kyc in finance tab

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/qr/ui/ShowQrActivity.java
Fixes #25
Adjusted Brightness to FULL for Show QR code Activity
> Adjusted Brightness to FULL for Show QR code Activity

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/base/BaseActivity.java
Fixes #150 #152 #153 #151 #157 
Locked orientation to portrait
**GIFS (the phone is held in landscape mode)**
> Locked Orientation to portrait

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/ui/TransferFragment.java
Fixes #155 
**Summary**
Added set error method to both Amount and VPA
**SCREENSHOT**
> Added set error method to both Amount and VPA

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/merchants/ui/MerchantsFragment.java
> fix:App crash while searching in trusted merchant fragmet

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/merchants/MerchantsContract.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/merchants/adapter/MerchantsAdapter.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/merchants/presenter/MerchantsPresenter.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/merchants/ui/MerchantsFragment.java
Fixes #184
Add documentation for merchants package
> Documentation for Presenter

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/faq/FAQContract.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/faq/FAQListAdapter.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/faq/presenter/FAQPresenter.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/faq/ui/FAQActivity.java
> added FAQ documentation

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/savedcards/CardsContract.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/savedcards/presenter/CardsPresenter.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/savedcards/ui/AddCardDialog.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/savedcards/ui/CardsAdapter.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/savedcards/ui/CardsFragment.java
> Saved Cards Documentation

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/injection/component/ActivityComponent.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/payments/ui/SendFragment.java
- mifospay/src/main/res/color/background_chip_state.xml
- mifospay/src/main/res/layout/fragment_send.xml
- mifospay/src/main/res/values/colors.xml
- mifospay/src/main/res/values/strings.xml
Fixes 
#134 
Summary 
Adding the send functionality in send section
> Integrated send section in payments

- build.gradle
Changes: Updated compile and target SDK versions of the app
Fixes #217
( Previous PR for this have some conflicts, So closed )
> Updated SDK versions

- README.md
> fix : Updated broken links

- mifospay/src/main/res/layout/fragment_send.xml
Fixes #329 
**Before Changes**
**After Changes**
> fix : Central alignment of Button and TextView in send fragment

- mifospay/src/main/res/layout/fragment_accounts.xml
- mifospay/src/main/res/layout/fragment_merchants.xml
> fix: Add scroll bar to Trusted Merchants screen and Account screen

- build.gradle
- core/build.gradle
- mifospay/build.gradle
> refactor : Added dependencies version in root project

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/merchants/presenter/MerchantsPresenter.java
> fix:Alphabetical order in Trusted Merchants

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/ui/TransferFragment.java
- mifospay/src/main/res/layout/fragment_transfer.xml
> fix:Amount column in Transfer fragment should accept up to 2 decimal digits in the amount

- mifospay/src/main/res/layout/activity_settings.xml
> fix : UI of buttons in settings activity

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/data/firebase/api/services/MifosPayInstanceIDService.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/injection/component/ApplicationComponent.java
> fix : App crashing on first build

- core/src/main/java/org/mifos/mobilewallet/core/domain/usecase/invoice/FetchInvoice.java
- mifospay/src/main/AndroidManifest.xml
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/base/BaseActivity.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/base/BaseActivityCallback.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/invoice/ui/InvoiceActivity.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/receipt/ui/ReceiptActivity.java
**fix: Memory leaks in Receipt and Invoice Activities
fix: Error handling while using the wrong deeplink addresses
fix: Added both activities as singleTask to avoid multiple instances.**
> fix: deeplink issues and improvements

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/common/ui/MakeTransferFragment.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/history/ui/HistoryFragment.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/BaseHomeContract.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/presenter/HomePresenter.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/ui/HomeFragment.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/payments/ui/SendFragment.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/qr/ui/ReadQrActivity.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/qr/ui/ShowQrActivity.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/utils/Constants.java
- mifospay/src/main/res/drawable/ic_flash_off.xml
- mifospay/src/main/res/drawable/ic_flash_on.xml
- mifospay/src/main/res/layout/activity_read_qr.xml
- mifospay/src/main/res/layout/activity_show_qr.xml
- mifospay/src/main/res/layout/fragment_history.xml
- mifospay/src/main/res/layout/fragment_home.xml
- mifospay/src/main/res/layout/fragment_make_transfer.xml
- mifospay/src/main/res/layout/fragment_send.xml
**feat: Tap to reveal balance in Home Screen**
**feat: Show more History button now works on Home Screen**
**feat: Added Flash Light in QR Scanner**
**feat: Added Animations**
**feat: Add the amount in QR, also changed the QR data fetching**
> Improved user experience

- README.md
Fixes #344 
Corrected the branch name in the cloning url of the readme file.
> Corrected the cloning url

- README.md
Fixes #339 
Grammatical error in readme file has been resolved.
> Grammatical error in readme file has been resolved

- config/quality/pmd/pmd-ruleset.xml
- core/src/main/java/org/mifos/mobilewallet/core/base/UseCaseThreadPoolScheduler.java
- core/src/main/java/org/mifos/mobilewallet/core/data/fineract/api/services/SavingsAccountsService.java
- core/src/main/java/org/mifos/mobilewallet/core/data/fineract/repository/FineractRepository.java
- core/src/main/java/org/mifos/mobilewallet/core/domain/usecase/account/DownloadTransactionReceipt.java
- core/src/main/java/org/mifos/mobilewallet/core/domain/usecase/account/FetchAccountTransaction.java
- core/src/main/java/org/mifos/mobilewallet/core/domain/usecase/invoice/FetchInvoice.java
- gradle/wrapper/gradle-wrapper.properties
- mifospay/build.gradle
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/data/local/PreferencesHelper.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/BaseHomeContract.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/presenter/HomePresenter.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/merchants/adapter/MerchantsAdapter.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/merchants/presenter/MerchantTransferPresenter.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/merchants/ui/MerchantTransferActivity.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/merchants/ui/MerchantsFragment.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/payments/ui/SendFragment.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/qr/ui/ShowQrActivity.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/receipt/ui/ReceiptActivity.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/registration/presenter/SignupPresenter.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/registration/ui/SignupActivity.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/savedcards/ui/AddCardDialog.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/utils/Constants.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/utils/PasswordStrength.java
Updated pmd-rulesets and sorted indentation-issues.
Fixes #573 and #566 
None
> fix : Travis build works now

- mifospay/src/main/res/layout/fragment_send.xml
> fix: Changed text sizes from dp to sp

- core/src/main/java/org/mifos/mobilewallet/core/domain/model/user/NewUser.java
- core/src/main/java/org/mifos/mobilewallet/core/utils/Constants.java
> Move new user role ids into Constants class

- mifospay/src/main/res/layout/activity_mobile_verification.xml
- mifospay/src/main/res/layout/fragment_kyc_lvl1.xml
> fix: Limit the digits of Mobile Number in Mobile Verification and KYC Registration level 1 Activities

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/notification/ui/NotificationActivity.java
- mifospay/src/main/res/layout/activity_notification.xml
- mifospay/src/main/res/values/strings.xml
> feat:Added empty view in Notification Activity

- mifospay/src/main/res/values/strings.xml
> Feat: Added Frequently Asked Questions

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/settings/ui/SettingsActivity.java
- mifospay/src/main/res/values/strings.xml
> feat: alert dialog box for log out button 

- README.md
Fixes #575
Modified readme file with newer instructions
> fix: modified readme with newer instructions

- .github/ISSUE_TEMPLATE.md
Improved the issue template so that is hides the hints in each section.
> Fixes not hidden issue template hints

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/bank/ui/LinkBankAccountActivity.java
- mifospay/src/main/res/layout/activity_link_bank_account.xml
> feat:Hide Popular Bank when search is pressed

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/registration/ui/SignupActivity.java
- mifospay/src/main/res/layout/activity_signup.xml
Fixes #610 
address line 2 is empty ![Screenshot_20191219-152255](https://user-images.githubusercontent.com/38397893/71181202-f37f2180-2273-11ea-982b-127d8563ab39.png)
> Fix #610 - Fixes UI inconsistencies in the sign up activity

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/faq/FAQContract.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/faq/ui/FAQActivity.java
> fix: removed unnecessary toasts in faq activity

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/editprofile/ui/EditProfileActivity.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/utils/DialogBox.java
Fixes #616
Made a utility class that can be called anywhere to make an Alert Dialog with less amount of code. Also replaced the alertDialog in one activity ```EditProfileActivity``` with the new utility class.
##
> feat: common function for all dialog boxes

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/presenter/HomePresenter.java
> fix: Transaction History shows empty recycler view on viewing last group of records

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/editprofile/ui/EditProfileActivity.java
> Fix: Keyboard closes on saving

- README.md
Corrected the inappropriate links.
> docs: Correct links in README file

- mifospay/src/main/res/layout/fragment_send.xml
- mifospay/src/main/res/values/integers.xml
> Fix: length limit of mobile number in send fragment

- .github/PULL_REQUEST_TEMPLATE.md
Improved the existing Pull Request Template.
Making a PR
Preview
> feat: improved the PR template

- mifospay/src/main/res/layout/activity_link_bank_account.xml
- mifospay/src/main/res/layout/activity_transaction_history.xml
> feat: Add scroll bars in Transaction History and Other Bank screen

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/settings/ui/SettingsActivity.java
- mifospay/src/main/res/values/strings.xml
Fixes #658 
Added alert box when user wants to disable account in SettingsActivity.
> fix: added alert box when user wants to disable account

- mifospay/src/main/res/layout/fragment_home.xml
Fixes #674 
Added scroll bar in transaction history 
> fix: added scroll bar in transaction history

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/qr/ui/ShowQrActivity.java
> Fixes #715 - added a check for zero value in ShowQrActivity

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/bank/ui/LinkBankAccountActivity.java
- mifospay/src/main/res/layout/activity_link_bank_account.xml
- mifospay/src/main/res/values/strings.xml
> fix: added function to show no bank when the bank option is not available

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/payments/ui/SendFragment.java
> Fix #726 - Added tests so that only fields of the section which is selected are checked

- mifospay/src/main/res/layout/fragment_history.xml
Fixes #713 
Added scroll bar in transaction history
> fix: added scroll bar in transaction fragment.xml

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/qr/ui/ShowQrActivity.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/settings/ui/SettingsActivity.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/utils/DialogBox.java
> Replaced android.app.AlertDialog with android.support.v7.app.AlertDialog in ShowQrActivity

- mifospay/src/main/res/layout-land/activity_login.xml
- mifospay/src/main/res/layout/activity_login.xml
Fixes #742 
Added scroll view as the parent view.
> fix:  ui issue in login activity

- mifospay/src/main/AndroidManifest.xml
- mifospay/src/main/res/layout/activity_login.xml
Fixes #748 
When user enter username and password user scroll up and click the login button
##
> fixes issue #748. Added ScrollView in Login Screen.

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/bank/ui/LinkBankAccountActivity.java
> Fixed the behaviour of the back button in LinkBankAccountActivity

- Screenshot.md
Fixes: #661
Added screen shots of the app
> fix: added all the screenshots of app

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/bank/fragment/OtpFragment.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/bank/fragment/UpiPinFragment.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/merchants/ui/MerchantsFragment.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/qr/ui/ShowQrActivity.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/receipt/ui/ReceiptActivity.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/registration/ui/MobileVerificationActivity.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/settings/ui/SettingsActivity.java
- mifospay/src/main/res/values/strings.xml
Fixes: #819
Removed all hardcoded strings from java files.
> fix:  removed all hardcoded strings in java files

- mifospay/src/main/res/layout/activity_faq.xml
Fixes: #654 
Added only scroll bar and didn't add function to cose FAQ bar as discussed in the previous pr
Pr number: https://github.com/openMF/mobile-wallet/pull/657
> fix: added scroll bar in FAQ activity

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/savedcards/presenter/CardsPresenter.java
> refactor : Simplified If statement to a single assignment in CardsPresenter

- core/src/main/java/org/mifos/mobilewallet/core/data/fineract/api/BaseURL.java
Fixes #754 API Endpoint fix
Changed the API Endpoint from `demo.openmf.org` to `demo.mifos.io`
##
> Fix #754: fixed the API endpoint

- mifospay/src/main/res/layout/item_specific_transaction.xml
> fix#752 - removed dividing line

- README.md
Fixes #879 
Add mifos pay logo in Readme
##
> Add mifos pay logo in Readme

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/qr/ui/ShowQrActivity.java
> Fixes #876 - VPA labeled correctly in ShowQrActivity

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/payments/ui/SendFragment.java
> Fix #841 - added transaction checks when transferring money 

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/ui/PaymentsFragment.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/utils/Utils.java
> Fixes #858 - Keyboard moves down when toggling from SendFragment to RequestFragment

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/merchants/presenter/MerchantTransferPresenter.java
> Fix #766 - added a check for null transferDetail

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/payments/ui/SendFragment.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/utils/Constants.java
Fixes #607 
Fixed the error message when the system is not able to find particular VPA or Mobile Number, it shows error accordingly. Earlier, it was just supporting VPA.
##
> fix: error message in send fragment

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/common/TransferContract.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/common/presenter/MakeTransferPresenter.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/common/ui/MakeTransferFragment.java
> fix#844 - disabled sheet dragging while transferring

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/payments/ui/SendFragment.java
> Fix #750 - Removed the call to showSwipeProgress after self account error occurs

- mifospay/src/main/AndroidManifest.xml
> Fix #759 - Removed redundant TransactionsHistoryActivity reference from the manifest

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/kyc/ui/KYCLevel1Fragment.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/registration/ui/MobileVerificationActivity.java
Fixes #453 
**Screenshots** 
**Mobile verification Activity**
**KYC Registration level 1 Activity**
> fix : Select a country pop-up dialog box is showing all the countries

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/base/BaseActivity.java
> fix : Remove redundant castings in the project

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/kyc/ui/KYCDescriptionFragment.java
> Fix #777 - variable names in KYCDescription now follow camel case convention

- mifospay/src/main/res/layout/activity_edit_profile.xml
Fixes #675
Added Input type to username, email,VPA.
> fix: added input type to username,email,vpa

- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/history/ui/TransactionDetailDialog.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/history/ui/adapter/HistoryAdapter.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/history/ui/adapter/SpecificTransactionsAdapter.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/ui/HomeFragment.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/receipt/ui/ReceiptActivity.java
- mifospay/src/main/java/org/mifos/mobilewallet/mifospay/utils/Utils.java
Fix #770
Currencies are now formatted by passing currency code and amount to the utils function which formats these currencies according to their currency code and also gives them an appropriate currency symbol
> Fix #770 - improved currency formatting

- .github/ISSUE_TEMPLATE.md
Improved the existing Issue Template.
> feat: improved the issue template
