mifospay/src/main/java/org/mifos/mobilewallet/mifospay/editprofile/ui/EditProfileActivity.java, mifospay/src/main/res/layout/activity_edit_profile.xml, mifospay/src/main/res/values/integers.xml
Fixes #76 
Please Add Summary of what changes you have made. (Optional)
The bug occurred because of country code which was added to the input. For now, only for input case, we format mobile number by excluding country code, so always if the number is correct it will be saved.
I've also added the length limit to the input which equals 15 characters (International standard).
=> Fix: #76 User can save correct number now

mifospay/src/main/res/layout/activity_edit_profile.xml
Fixes #89
The profile picture is now able to be scrolled away, leaving room for other content.
=> Fix #89: Edit Profile Photo Header Should Not Be Persistent

mifospay/src/main/res/layout/activity_edit_profile.xml
Fixes #61 
**Screenshot:**
Changed the hint text for the ```New Passcode``` text field in Profile Activity.
=> fix #61 :Changed hint text for 'New Passcode' text field

mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/adapter/PaymentsAdapter.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/ui/MainActivity.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/ui/PaymentsFragment.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/payments/ui/HistoryFragment.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/payments/ui/InvoicesFragment.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/payments/ui/RequestFragment.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/payments/ui/SendFragment.java, mifospay/src/main/res/drawable/ic_history_white_24dp.xml, mifospay/src/main/res/drawable/ic_outline_description_24dp.xml, mifospay/src/main/res/layout/fragment_history.xml, mifospay/src/main/res/layout/fragment_invoices.xml, mifospay/src/main/res/layout/fragment_payments.xml, mifospay/src/main/res/layout/fragment_request.xml, mifospay/src/main/res/layout/fragment_send.xml, mifospay/src/main/res/values/strings.xml
Fixes #122 
- Redesign Payments Tab and transfer fragment has been moved to the Finance tab
- I have used a dummy TextView in the ViewPager
Checks:
=> Feat: Redesign Payments Tab

mifospay/src/main/res/layout/activity_settings.xml, mifospay/src/main/res/values/strings.xml
Fixes #313 
**Before**
**After**
=> fix : Typo in settings activity

core/src/main/java/org/mifos/mobilewallet/core/utils/DateHelper.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/editprofile/ui/EditProfileActivity.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/ui/TransferFragment.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/kyc/ui/KYCLevel2Fragment.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/receipt/ui/ReceiptActivity.java
Fixes #415 
**Summary**
Removed redundant string operations.
Removed unnecessary return statements.
=> fix : Removed redundant code constructs

mifospay/src/main/res/layout/fragment_debit_card.xml
Fixes #382 
**Before Changes**
**After Changes**
**Summary** 
Decreased the padding of the linear layout from 20dp to 12 dp in `fragment_debit_card.xml`.
=> fix : The fourth digit of expiry year is now visible to user

mifospay/build.gradle
Fixes #565 
Added firebase:core dependency in build/mifospay to eliminate warnings and errors
=> fix: added firebase:core in build/mifospay to eliminate warnings

mifospay/src/main/java/org/mifos/mobilewallet/mifospay/editprofile/ui/EditProfileActivity.java
Fixes #582 
Removed the hints when the mobile number is clicked
=> fix: removed hints after mobile number is pressed in EditProfile

mifospay/src/main/res/layout/fragment_send.xml
=> Fix: Add non-integers in mobile number

README.md
Fixes #618 
Added Travis CI commands in Readme
=> added travis ci commands in readme

mifospay/src/main/res/layout/activity_mobile_verification.xml
Fixes #656 
The maximum length of OTP is fixed to 6.
=> fix : limiting OTP length to 6

mifospay/src/main/res/drawable/ic_arrow_back.xml
Fixes #695
Changed the color of the back arrow from black to white.
=>  changed the color of back arrow to white

mifospay/src/main/java/org/mifos/mobilewallet/mifospay/auth/ui/LoginActivity.java
Fixes #705 
Added code when google sign in fails, it leads to the same activity
=>  fix: returns to the previous page if google sign in not verified

mifospay/src/main/res/layout/fragment_accounts.xml
Fixes #731 **Add Account** text in Account Fragment is now completely visible on long displays
=> Fix #731: Add account button text not visible completely

mifospay/src/main/java/org/mifos/mobilewallet/mifospay/utils/DialogBox.java
When you open the edit Profile Dialog box, and then immediately dismiss it (don't make any profile changes), the app crashes because of a NullPointerException. This PR fixes this bug. Please refer #643 for more.
=> fix: Edit Profile dialog crashes when dismissed without any changes.

mifospay/src/main/res/layout/fragment_send.xml
=> Fix #822 - Cursor color now matches with the overall theme

mifospay/src/main/java/org/mifos/mobilewallet/mifospay/history/HistoryContract.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/history/presenter/SpecificTransactionsPresenter.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/history/presenter/TransactionDetailPresenter.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/history/ui/SpecificTransactionsActivity.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/history/ui/TransactionDetailDialog.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/invoice/InvoiceContract.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/invoice/presenter/InvoicesPresenter.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/invoice/ui/InvoicesFragment.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/merchants/MerchantsContract.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/merchants/presenter/MerchantsPresenter.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/merchants/ui/MerchantsFragment.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/savedcards/CardsContract.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/savedcards/presenter/CardsPresenter.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/savedcards/ui/CardsFragment.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/utils/Constants.java, mifospay/src/main/res/layout/activity_specific_transactions.xml, mifospay/src/main/res/layout/dialog_transaction_detail.xml, mifospay/src/main/res/layout/fragment_cards.xml, mifospay/src/main/res/layout/fragment_invoices.xml, mifospay/src/main/res/values/strings.xml
Fixes #808 #806 #798 
For #798 
For #806 and #808 
For #798 
Added dedicated Views for reporting error in fetching data, added `ProgressBar` and removed unnecessary toast messages in `InvoicesFragment` and `CardsFragment`.
For #806 
`ProgressBar` added and also now in case of any error in fetching process toast message pops up notifying the user about the same
For #808 
Added a dedicated view to notify user if any error occurs while fetching the specific transactions.
Also added a progress bar for showing for the fetching process
##
=> fixes 808, 806 and 798

mifospay/src/main/java/org/mifos/mobilewallet/mifospay/auth/ui/LoginActivity.java, mifospay/src/main/res/layout/activity_login.xml
Fixes #762 
Soft Keyboard now hides on clicking anywhere and not just on clicking the system back button.
=> fixes #762 - Soft Keyboard hides on clicking anywhere

mifospay/src/main/java/org/mifos/mobilewallet/mifospay/qr/ui/ShowQrActivity.java
Fix: #831
Added credential before the data in ShowQrFragment
=>  fix: added credential before the data

mifospay/src/main/java/org/mifos/mobilewallet/mifospay/auth/ui/LoginActivity.java
Fixes #889 
The application doesn't crash anymore because `Utils.hideSoftKeyboard(context)` is not called if there's no item in focus, which earlier made the application crash
##
=> fix#889 - app does not crash on tapping on background

mifospay/src/main/java/org/mifos/mobilewallet/mifospay/bank/ui/BankAccountDetailActivity.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/bank/ui/LinkBankAccountActivity.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/bank/ui/SetupUpiPinActivity.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/base/BaseActivity.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/base/BaseActivityCallback.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/base/BaseFragment.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/common/ui/SearchActivity.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/faq/ui/FAQActivity.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/history/ui/SpecificTransactionsActivity.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/invoice/ui/InvoiceActivity.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/merchants/ui/MerchantTransferActivity.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/notification/ui/NotificationActivity.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/qr/ui/ReadQrActivity.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/qr/ui/ShowQrActivity.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/receipt/ui/ReceiptActivity.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/registration/ui/MobileVerificationActivity.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/registration/ui/SignupActivity.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/settings/ui/SettingsActivity.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/utils/Constants.java, mifospay/src/main/res/drawable/ic_arrow_back_black_24dp.xml, mifospay/src/main/res/drawable/ic_arrow_back_white_24dp.xml
Fixes #702 
**Previous**
**After**
Added a single function for setting back navigation colour according to the UI need.
##
=> fix:back navigation color change in various activity

mifospay/src/main/java/org/mifos/mobilewallet/mifospay/bank/presenter/DebitCardPresenter.java, mifospay/src/main/res/values/strings.xml
Fixes #857 
Debit Card Number count is less than 12  : 
When Debit Card Number count is more than 19  :
When Debit Card Number is in range i.e. 12-19  :
If the Debit Card Number entered is not sufficient i.e. not in the range 12 - 19, it will show a toast message i.e. "Invalid Debit Card".
##
=> Shows Toast when debit card number's count is not in range of 12-19

mifospay/src/main/java/org/mifos/mobilewallet/mifospay/savedcards/ui/AddCardDialog.java
Fixes #872
Now the Toast message is shown only when the EditText details are valid but the card has expired.
##
=> fix#872 - AddCardDialog: Toast message shown only when data entered is valid but card has expired

mifospay/src/main/java/org/mifos/mobilewallet/mifospay/registration/ui/SignupActivity.java, mifospay/src/main/res/values/strings.xml
Fixes #252 
* Made a validateEmail call in the SignUpActivity.java 
* Added the displayed string to the strings.xml
**Note** :-> Currently only a function call is made, but the corresponding file(the one that contains that function) will also be converted to kt. if suggested.
##
=> feat: Implemented email pattern Validation in SignUp Process

mifospay/src/main/AndroidManifest.xml
=> Fix #774 - bottom navigation bar does not move up with the keyboard

mifospay/src/main/java/org/mifos/mobilewallet/mifospay/password/presenter/EditPasswordPresenter.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/utils/Constants.java
Fixes #612 
Added a toast which shows up if the user enters the same password as the new password.
##
=> fix: new password can't be the same as old password toast

mifospay/src/main/java/org/mifos/mobilewallet/mifospay/receipt/presenter/ReceiptPresenter.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/receipt/ui/ReceiptActivity.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/utils/Constants.java, mifospay/src/main/java/org/mifos/mobilewallet/mifospay/utils/Toaster.java, mifospay/src/main/res/xml/provider_paths.xml
=> Fix #788 - added option to view receipt when downloaded
